/*
 *
 * Generated by ChatGTP - doesn't work
 
Eduardo Flores
in rust, define a function with a mutable int variable and two closures, one that increments the variable and one that returns its value

... 

Eduardo Flores
the closures should be defined inside the function and must be it's return value

*/


fn manipulate_integer() -> (i32, impl FnMut() -> i32, impl FnMut()) {
    let mut value = 0;

    let increment = move || { value += 1; value };
    let get_value = move || value = value;

    (value, increment, get_value)
}

fn main() {
    let (mut value, mut increment, mut get_value) = manipulate_integer();

    println!("Initial value: {}", value); // Prints "Initial value: 0"

    increment();
    println!("Value after incrementing: {}", get_value()); // Prints "Value after incrementing: 1"

    increment();
    increment();
    println!("Value after incrementing again: {}", get_value()); // Prints "Value after incrementing again: 3"
}


